### ISSUE TITLE
Vraag: API-09

### ISSUE THREAD

**Issue by JostCrow** [Logius-standaarden/API-Design-Rules#113]
```
API-09: Implement custom representation if supported

Provide a comma-separated list of field names using the query parameter fields te retrieve a custom representation. In case non-existent field names are passed, a 400 Bad Request error message is returned.
```

Hoe is dit in de OAS 3 specificatie terug te vinden?
Ik kan hier niet uit de standaard specificatie niets vinden waaruit duidelijk wordt waar in de spec dit veld te vinden is.

**Comment by JostCrow** [comment]
Zou iemand hier meer duidlijkheid over kunnen geven hoe dit zou moeten werken in de API spec?

**Comment by fterpstra** [comment]
@joostfarla kan jij hier iets over zeggen?

**Comment by JostCrow** [comment]
Zou iemand nog antwoord kunnen geven op deze vraag? Dan weet ik ook of de implementatie die hievan gedaan is goed is of niet.

**Comment by joostfarla** [comment]
@JostCrow deze design rule is hier te vinden: https://geonovum.github.io/KP-APIs/API-strategie-extensies/#custom-representation. Maar zoals je zult zien is de uitwerking nog erg summier. Het komt erop neer dat je een query parameter hebt met de naam `fields`, met als waarde een comma-gescheiden lijst met attribuutnamen. Daarbij is het wel belangrijk om te weten dat de exacte details van deze design rule nog ter discussie staan, zie ook de conversaties onder issue #61 en #44. 

In een OAS3 spec zou de huidige invulling er ongeveer zo uit komen te zien:

```yaml
- name: fields
  in: query
  required: false
  schema:
    type: array
    explode: false    
    items:
      type: string
```

Eventueel zou je het `items` schema uit kunnen breiden met een `enum` constraint om de te gebruiken waardes te beperken.

**Comment by JostCrow** [comment]
@joostfarla Dankje voor je antwoord. Het lijkt goed overeen te komen met wat ik zelf al dacht. Ik heb het nu geimplementeerd als volgende:

```
"parameters": [
                    {
                        "name": "fields",
                        "in": "query",
                        "description": "give a list of fields that need to be returned",
                        "schema": {
                            "type": "string",
                            "enum": ["uuid", "api_endpoint", "sessions"]
                        }
                    },
]
```
Ik ga er zelf vanuit dat er een enum moet zijn. Aangezien het volledig is om ook aan te bieden op welke velden er gefilterd kan worden aangezien het in de beschrijving lijkt alsof er staat dat de velden meegeleverd moeten worden.

**Comment by joostfarla** [comment]
@JostCrow in jouw voorbeeld mis ik de wrapping binnen een array, waardoor de API nu maar 1 waarde accepteert. De array config in JSON ziet er als volgt uit (gelijk aan YAML voorbeeld hierboven):
```json
                "parameters": [
                    {
                        "name": "fields",
                        "in": "query",
                        "description": "give a list of fields that need to be returned",
                        "schema": {
                            "type": "array",
                            "explode": false,
                            "items": {
                                "type": "string",
                                "enum": ["uuid", "api_endpoint", "sessions"]
                            }
                        }
                    }
                ]
```

De `explode` setting is nodig om er een comma-separated string van te maken.

**Comment by JostCrow** [comment]
Ja dat klopt inderdaad. Het moet inderdaad een array zijn.
