### ISSUE TITLE
Versionering

### ISSUE THREAD

**Issue by jasperroes** [Logius-standaarden/API-Design-Rules#36]
Opmerking via review formulier: 

Afnemers kunnen zelf kiezen wanneer ze overstappen mits het gaat om een major release. Als het een minor release is kunnen ze de overstap alleen voorkomen door bewust een versie mee te geven.Vervolgens moeten ze deze extra header ook weer bewust uit gaan zetten en dan wel voordat de oude versie wordt uitgezet. Dat is wel een verschil.Het is voorstelbaar dat een API in een korte periode meerdere patches krijgt, dit kan ook betekenen dat het niet altijd alleen de recentste versies zijn die benaderbaar zijn.Ik kan me ook voorstellen dat je afnemers wel de keuze wilt geven in major/minor versions maar niet in patch versions.

**Comment by joostfarla** [comment]
Deze is reeds beslecht in de vastgestelde versie van de design rules (zie https://publicatie.centrumvoorstandaarden.nl/api/adr/#versioning). Een minor of patch release **vervangt** de vorige versie. Er is dus binnen een major versie altijd maar 1 minor/patch-versie in productie. Bestaande afnemers gaan automatisch en gelijktijdig (even afgezien van eventuele blue-green deployments) over naar een nieuwe versie. Er is geen request header om een specifieke minor/patch release te benaderen. De afnemer heeft hier dus geen invloed op.
